# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfapp < Formula
  desc "A TUI Terraform management application"
  homepage "https://github.com/sapasapasapa/tfapp"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sapasapasapa/tfapp/releases/download/v0.2.4/tfapp_Darwin_x86_64.zip"
      sha256 "b426506ca07cabc5c2fffeefade391f9b32d979337a5a322dd7dbf766ad1a8e2"

      def install
        bin.install "tfapp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sapasapasapa/tfapp/releases/download/v0.2.4/tfapp_Darwin_arm64.zip"
      sha256 "4ebcc65076f51f37cfae8a8114a789842bd97d3676b899aa8a95a6f00996ae67"

      def install
        bin.install "tfapp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sapasapasapa/tfapp/releases/download/v0.2.4/tfapp_Linux_x86_64.tar.gz"
        sha256 "322ce991646d6cb4f192a580bb6bdf0a67f429f046c3464e6be93dbbc05ab661"

        def install
          bin.install "tfapp"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sapasapasapa/tfapp/releases/download/v0.2.4/tfapp_Linux_arm64.tar.gz"
        sha256 "50958620d3b22244d083c1d0201ba546dae0914a152e114f9b543faeb4b042a3"

        def install
          bin.install "tfapp"
        end
      end
    end
  end

  test do
    system "#{bin}/tfapp", "--version"
  end
end
